### ISSUE TITLE
[Watchdog Crash] Structure piece NBTs are old and thus, running DataFixerUpper on them when they spawn

### ISSUE THREAD

**Issue by dandin87** [Aureljz/WhenDungeonsArise--Fabric#12]
Reposting from CF issue Tracker as this is really affecting a lot of AoF6 servers. We would prefer not to remove Dungeons Arise from the pack.
https://legacy.curseforge.com/minecraft/mc-mods/when-dungeons-arise/issues/123

Several users in the All of Fabric 6 discord were having issues where the server is generating a chunk and then times out after being stuck for over a minute. The watchdog printed out the stacktrace of what every thread was stuck on when the deadlock occurred: 
```
	at net.aurelj.dungeons_arise.structures.ModifiedStructurePoolBasedGenerator.generate(ModifiedStructurePoolBasedGenerator.java:86)
	at net.aurelj.dungeons_arise.structures.WDAGenericStructures.method_38676(WDAGenericStructures.java:103)
```
https://aofpaste.com/iwimicagar.rb

This mod was created to catch this issue. https://www.curseforge.com/minecraft/mc-mods/fullstack-watchdog

From this, it looks like there's a strange issue where as Dungeon Arise's structure piece NBTs are loaded, DataFixerUpper sees the NBTs are in an older format and attempts to upgrade them to the current Minecraft version's NBT format. But in doing so, it took too longer somehow and server times out.

What you can do is run this Structure Fixer program on the NBT files themselves to automatically upgrade them all to 1.19.2's format which should in theory significantly reduce DFU lag or at least, make it skip looking at the pieces entirely
https://github.com/jaskarth/structure-fixer/releases

Image of some info that might help with running it:
![BWGpR0a](https://user-images.githubusercontent.com/9329117/233746452-ac01fb59-8da4-4128-a34b-f9486e4886a4.png)

**Comment by Aureljz** [comment]
Hey! I'll take a look at this and release a patched version shortly.

**Comment by Aureljz** [comment]
New update patches DataFixerUpper versions: https://legacy.curseforge.com/minecraft/mc-mods/when-dungeons-arise-fabric/files/4502600

If the issue persists, I recommend you to try disable "dungeons_arise:keep_kayra" until we find the actual cause.
