### ISSUE TITLE
Configure which structures can spawn?

### ISSUE THREAD

**Issue by NolanHewitt** [Aureljz/WhenDungeonsArise--Fabric#28]
Is there any way to disable some of the structures from spawning?

**Comment by plancha2002** [comment]
Response from creator on curse forge: This mod is datapack driven, so we use datapacks to configure it. Check out [Spacing Tweaks](https://legacy.curseforge.com/minecraft/texture-packs/when-dungeons-arise-spacing-tweaks) to change spawnrates, or [No Flying Structures](https://legacy.curseforge.com/minecraft/texture-packs/when-dungeons-arise-no-flying-structures) as a template to change biomes. There's also [Loot Tweaks](https://legacy.curseforge.com/minecraft/texture-packs/when-dungeons-arise-loot-tweaks) to modify loot to a more vanilla alternative. Anyway, the mod is highly configurable.
